### ISSUE TITLE
Make substat_name arg optional

### ISSUE THREAD

**Issue by lhehnke** [CorrelAid/datenguideR#6]

**Comment by lhehnke** [comment]
@favstats added a workaround to this issue. It would be great if you could check whether this is a good (enough) solution for our first release or whether you can implement a more efficient and/or elegant one.

**Comment by favstats** [comment]
A (preliminary) implementation of this was done here: https://github.com/CorrelAid/datenguideR/commit/56096e282b4f96a42c462072321345c7f68fdfcf

*HOWEVER* We should keep this issue open I think. It's sort of experimental and not the ideal way to fix this.
